// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="axil_conv2D_axil_conv2D,hls_ip_2024_1_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.508000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=493,HLS_SYN_LUT=746,HLS_VERSION=2024_1_2}" *)

module axil_conv2D (
        ap_clk,
        ap_rst_n,
        s_axi_BUS1_AWVALID,
        s_axi_BUS1_AWREADY,
        s_axi_BUS1_AWADDR,
        s_axi_BUS1_WVALID,
        s_axi_BUS1_WREADY,
        s_axi_BUS1_WDATA,
        s_axi_BUS1_WSTRB,
        s_axi_BUS1_ARVALID,
        s_axi_BUS1_ARREADY,
        s_axi_BUS1_ARADDR,
        s_axi_BUS1_RVALID,
        s_axi_BUS1_RREADY,
        s_axi_BUS1_RDATA,
        s_axi_BUS1_RRESP,
        s_axi_BUS1_BVALID,
        s_axi_BUS1_BREADY,
        s_axi_BUS1_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_BUS1_DATA_WIDTH = 32;
parameter    C_S_AXI_BUS1_ADDR_WIDTH = 17;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_BUS1_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_BUS1_AWVALID;
output   s_axi_BUS1_AWREADY;
input  [C_S_AXI_BUS1_ADDR_WIDTH - 1:0] s_axi_BUS1_AWADDR;
input   s_axi_BUS1_WVALID;
output   s_axi_BUS1_WREADY;
input  [C_S_AXI_BUS1_DATA_WIDTH - 1:0] s_axi_BUS1_WDATA;
input  [C_S_AXI_BUS1_WSTRB_WIDTH - 1:0] s_axi_BUS1_WSTRB;
input   s_axi_BUS1_ARVALID;
output   s_axi_BUS1_ARREADY;
input  [C_S_AXI_BUS1_ADDR_WIDTH - 1:0] s_axi_BUS1_ARADDR;
output   s_axi_BUS1_RVALID;
input   s_axi_BUS1_RREADY;
output  [C_S_AXI_BUS1_DATA_WIDTH - 1:0] s_axi_BUS1_RDATA;
output  [1:0] s_axi_BUS1_RRESP;
output   s_axi_BUS1_BVALID;
input   s_axi_BUS1_BREADY;
output  [1:0] s_axi_BUS1_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [12:0] image_out_address0;
reg    image_out_ce0;
reg    image_out_we0;
reg   [15:0] image_out_d0;
wire   [15:0] image_out_q0;
wire   [0:0] bias;
wire    grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_start;
wire    grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_done;
wire    grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_idle;
wire    grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_ready;
wire   [12:0] grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_address0;
wire    grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_ce0;
wire    grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_we0;
wire   [15:0] grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_d0;
wire    grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_start;
wire    grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_done;
wire    grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_idle;
wire    grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_ready;
wire   [12:0] grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_address0;
wire    grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_ce0;
wire    grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_we0;
wire   [15:0] grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_d0;
wire   [10:0] grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_address0;
wire    grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_ce0;
wire    grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_we0;
wire   [15:0] grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_d0;
reg    grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_start_reg = 1'b0;
#0 grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_start_reg = 1'b0;
end

axil_conv2D_axil_conv2D_Pipeline_loop_i_loop_j grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_start),
    .ap_done(grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_done),
    .ap_idle(grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_idle),
    .ap_ready(grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_ready),
    .image_out_address0(grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_address0),
    .image_out_ce0(grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_ce0),
    .image_out_we0(grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_we0),
    .image_out_d0(grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_d0)
);

axil_conv2D_axil_conv2D_Pipeline_loop_n grp_axil_conv2D_Pipeline_loop_n_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_start),
    .ap_done(grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_done),
    .ap_idle(grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_idle),
    .ap_ready(grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_ready),
    .image_out_address0(grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_address0),
    .image_out_ce0(grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_ce0),
    .image_out_we0(grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_we0),
    .image_out_d0(grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_d0),
    .image_out_q0(image_out_q0),
    .max_out_address0(grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_address0),
    .max_out_ce0(grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_ce0),
    .max_out_we0(grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_we0),
    .max_out_d0(grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_d0)
);

axil_conv2D_BUS1_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_BUS1_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_BUS1_DATA_WIDTH ))
BUS1_s_axi_U(
    .AWVALID(s_axi_BUS1_AWVALID),
    .AWREADY(s_axi_BUS1_AWREADY),
    .AWADDR(s_axi_BUS1_AWADDR),
    .WVALID(s_axi_BUS1_WVALID),
    .WREADY(s_axi_BUS1_WREADY),
    .WDATA(s_axi_BUS1_WDATA),
    .WSTRB(s_axi_BUS1_WSTRB),
    .ARVALID(s_axi_BUS1_ARVALID),
    .ARREADY(s_axi_BUS1_ARREADY),
    .ARADDR(s_axi_BUS1_ARADDR),
    .RVALID(s_axi_BUS1_RVALID),
    .RREADY(s_axi_BUS1_RREADY),
    .RDATA(s_axi_BUS1_RDATA),
    .RRESP(s_axi_BUS1_RRESP),
    .BVALID(s_axi_BUS1_BVALID),
    .BREADY(s_axi_BUS1_BREADY),
    .BRESP(s_axi_BUS1_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .bias(bias),
    .max_out_address0(grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_address0),
    .max_out_ce0(grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_ce0),
    .max_out_we0(grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_we0),
    .max_out_d0(grp_axil_conv2D_Pipeline_loop_n_fu_64_max_out_d0),
    .image_out_address0(image_out_address0),
    .image_out_ce0(image_out_ce0),
    .image_out_we0(image_out_we0),
    .image_out_d0(image_out_d0),
    .image_out_q0(image_out_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_ready == 1'b1)) begin
            grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_ready == 1'b1)) begin
            grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        image_out_address0 = grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        image_out_address0 = grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_address0;
    end else begin
        image_out_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        image_out_ce0 = grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        image_out_ce0 = grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_ce0;
    end else begin
        image_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        image_out_d0 = grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        image_out_d0 = grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_d0;
    end else begin
        image_out_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        image_out_we0 = grp_axil_conv2D_Pipeline_loop_n_fu_64_image_out_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        image_out_we0 = grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_image_out_we0;
    end else begin
        image_out_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_start = grp_axil_conv2D_Pipeline_loop_i_loop_j_fu_58_ap_start_reg;

assign grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_start = grp_axil_conv2D_Pipeline_loop_n_fu_64_ap_start_reg;

endmodule //axil_conv2D
