set_property SRC_FILE_INFO {cfile:/home/ares/Desktop/CO-Proj/Labs/Lab1/lab1_vivado/lab1_vivado.srcs/constrs_1/new/debug.xdc rfile:../../../lab1_vivado.srcs/constrs_1/new/debug.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list lab1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {lab1_i/axil_conv2D_0/s_axi_BUS1_WSTRB[0]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WSTRB[1]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WSTRB[2]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WSTRB[3]}]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[0]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[1]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[2]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[3]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[4]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[5]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[6]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[7]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[8]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[9]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[10]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[11]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[12]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[13]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[14]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[15]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[16]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[17]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[18]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[19]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[20]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[21]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[22]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[23]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[24]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[25]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[26]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[27]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[28]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[29]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[30]} {lab1_i/axil_conv2D_0/s_axi_BUS1_WDATA[31]}]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 15 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[0]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[1]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[2]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[3]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[4]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[5]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[6]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[7]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[8]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[9]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[10]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[11]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[12]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[13]} {lab1_i/axil_conv2D_0/s_axi_BUS1_ARADDR[14]}]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 13 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[2]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[3]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[4]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[5]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[6]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[7]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[8]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[9]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[10]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[11]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[12]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[13]} {lab1_i/axil_conv2D_0/s_axi_BUS1_AWADDR[14]}]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[0]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[1]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[2]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[3]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[4]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[5]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[6]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[7]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[8]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[9]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[10]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[11]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[12]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[13]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[14]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[15]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[16]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[17]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[18]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[19]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[20]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[21]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[22]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[23]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[24]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[25]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[26]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[27]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[28]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[29]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[30]} {lab1_i/axil_conv2D_0/s_axi_BUS1_RDATA[31]}]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list lab1_i/axil_conv2D_0/s_axi_BUS1_ARREADY]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list lab1_i/axil_conv2D_0/s_axi_BUS1_ARVALID]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list lab1_i/axil_conv2D_0/s_axi_BUS1_AWREADY]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list lab1_i/axil_conv2D_0/s_axi_BUS1_AWVALID]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list lab1_i/axil_conv2D_0/s_axi_BUS1_BREADY]]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list lab1_i/axil_conv2D_0/s_axi_BUS1_BVALID]]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list lab1_i/axil_conv2D_0/s_axi_BUS1_RREADY]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list lab1_i/axil_conv2D_0/s_axi_BUS1_RVALID]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list lab1_i/axil_conv2D_0/s_axi_BUS1_WREADY]]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list lab1_i/axil_conv2D_0/s_axi_BUS1_WVALID]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
