domain_path: /home/ares/Desktop/CO-Proj/Labs/Lab1/vitis_better/platform_3ip_input/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /home/ares/tools/Xilinx/Vitis/2024.1/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
