# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab1_better/lab1_better.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_better || ORIG_REF_NAME==lab1_better} -quiet] -quiet

# IP: bd/lab1_better/ip/lab1_better_processing_system7_0_0/lab1_better_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_better_processing_system7_0_0 || ORIG_REF_NAME==lab1_better_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab1_better/ip/lab1_better_axil_conv2D_0_0/lab1_better_axil_conv2D_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_better_axil_conv2D_0_0 || ORIG_REF_NAME==lab1_better_axil_conv2D_0_0} -quiet] -quiet

# IP: bd/lab1_better/ip/lab1_better_auto_pc_0/lab1_better_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_better_auto_pc_0 || ORIG_REF_NAME==lab1_better_auto_pc_0} -quiet] -quiet

# IP: bd/lab1_better/ip/lab1_better_ps7_0_axi_periph_0/lab1_better_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_better_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab1_better_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab1_better/ip/lab1_better_rst_ps7_0_100M_0/lab1_better_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_better_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab1_better_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/ares/Desktop/CO-Proj/Labs/Lab1/lab_1better_vivado/lab_1better_vivado.gen/sources_1/bd/lab1_better/lab1_better_ooc.xdc
