# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/debug.xdc

# Block Designs: bd/lab1/lab1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1 || ORIG_REF_NAME==lab1} -quiet] -quiet

# IP: bd/lab1/ip/lab1_processing_system7_0_0/lab1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_processing_system7_0_0 || ORIG_REF_NAME==lab1_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab1/ip/lab1_axil_conv2D_0_0/lab1_axil_conv2D_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_axil_conv2D_0_0 || ORIG_REF_NAME==lab1_axil_conv2D_0_0} -quiet] -quiet

# IP: bd/lab1/ip/lab1_auto_pc_0/lab1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_auto_pc_0 || ORIG_REF_NAME==lab1_auto_pc_0} -quiet] -quiet

# IP: bd/lab1/ip/lab1_ps7_0_axi_periph_0/lab1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab1/ip/lab1_rst_ps7_0_100M_0/lab1_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab1_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/ares/Desktop/CO-Proj/Labs/Lab1/lab1_vivado/lab1_vivado.gen/sources_1/bd/lab1/lab1_ooc.xdc
