# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ip_3/ip_3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_3 || ORIG_REF_NAME==ip_3} -quiet] -quiet

# IP: bd/ip_3/ip/ip_3_processing_system7_0_0/ip_3_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_3_processing_system7_0_0 || ORIG_REF_NAME==ip_3_processing_system7_0_0} -quiet] -quiet

# IP: bd/ip_3/ip/ip_3_axil_conv2D_0_0/ip_3_axil_conv2D_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_3_axil_conv2D_0_0 || ORIG_REF_NAME==ip_3_axil_conv2D_0_0} -quiet] -quiet

# IP: bd/ip_3/ip/ip_3_axil_conv2D_1_0/ip_3_axil_conv2D_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_3_axil_conv2D_1_0 || ORIG_REF_NAME==ip_3_axil_conv2D_1_0} -quiet] -quiet

# IP: bd/ip_3/ip/ip_3_axil_conv2D_2_0/ip_3_axil_conv2D_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_3_axil_conv2D_2_0 || ORIG_REF_NAME==ip_3_axil_conv2D_2_0} -quiet] -quiet

# IP: bd/ip_3/ip/ip_3_xbar_0/ip_3_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_3_xbar_0 || ORIG_REF_NAME==ip_3_xbar_0} -quiet] -quiet

# IP: bd/ip_3/ip/ip_3_ps7_0_axi_periph_0/ip_3_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_3_ps7_0_axi_periph_0 || ORIG_REF_NAME==ip_3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ip_3/ip/ip_3_rst_ps7_0_100M_0/ip_3_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_3_rst_ps7_0_100M_0 || ORIG_REF_NAME==ip_3_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ip_3/ip/ip_3_auto_pc_0/ip_3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_3_auto_pc_0 || ORIG_REF_NAME==ip_3_auto_pc_0} -quiet] -quiet

# XDC: /home/ares/Desktop/CO-Proj/Labs/Lab1/vitis_better/viviado_3ip/viviado_3ip.gen/sources_1/bd/ip_3/ip_3_ooc.xdc
